<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function os2udoglaer_preprocess_page(&$variables) {
  // Add meta tag for noindex, nofollow
  // This is done in theme layer to avoid adding metatag to transform API responses
  $variables['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'robots',
        'content' => 'noindex, nofollow',
      ],
    ],
    'noindex_nofollow',
  ];
}
