<?php

use Drupal\os2uol_domain\Os2uolDomain;
use Drupal\transform_api\Transform\EntityTransform;
use Drupal\transform_api_views\Transform\ViewTransform;

function os2uol_transform_plugins_block_content_transform_alter(&$transformation): void {
  if (empty($transformation)) {
    return;
  }

  if ($transformation['bundle'] == 'appetizer') {
    $transform_mode = 'small';
    if ($transformation['transform_mode'] === 'width_100') {
      $transform_mode = 'default';
    }

    $transformation['appetizer_size'] = $transform_mode;
  }

  if ($transformation['bundle'] == 'application_form') {
    $domain_array = [];

    /** @var \Drupal\domain\DomainNegotiator $domain_negotiator */
    $domain_negotiator = \Drupal::service('domain.negotiator');

    // Add current and default domain to transformation.
    $domain_array[] = $domain_negotiator->getActiveId();

    if ($domain_negotiator->getActiveId() !== Os2uolDomain::DEFAULT_DOMAIN_ID) {
      $domain_array[] = Os2uolDomain::DEFAULT_DOMAIN_ID;
    }

    $transformation['field_domain_access'] = $domain_array;
  }
}

function os2uol_transform_plugins_node_transform_alter(&$transformation) {
  if (empty($transformation)) {
    return;
  }
  // Check if user role is provider.
  if ($transformation['#entity']->get('uid')->entity->hasRole('course_provider')) {
    // Add user transform object to transformation.
    $transformation['provider'] = new EntityTransform($transformation['#entity']->get('uid')->entity, 'courses');
  }
  // Check if user role is provider.
  if ($transformation['#entity']->get('uid')->entity->hasRole('corporation')) {
    // Add user transform object to transformation.
    $transformation['corporation'] = new EntityTransform($transformation['#entity']->get('uid')->entity, 'courses');
  }
  // Add entity link to transformation.
  $transformation['link'] = $transformation['#entity']->toUrl()->toString();
  // Add entity bundle label to transformation.
  $transformation['bundle_label'] = $transformation['#entity']->type->entity->label();
  // Add created date formatted with os2date to transformation.
  $transformation['created'] = \Drupal::service('date.formatter')->format($transformation['#entity']->get('created')->value, 'os2date');

  // Check if transformation is full and set is_frontpage variable if current page is set as frontpage.
  if ($transformation['transform_mode'] === 'full') {
    if (\Drupal::config('system.site')->get('page.front') === '/node/' . $transformation['#entity']->id()) {
      $transformation['is_frontpage'] = TRUE;
    } else {
      $transformation['is_frontpage'] = FALSE;
    }
  }
}

/**
 * Implements hook_TRANSFORM_TYPE_transform_alter().
 */
function os2uol_transform_plugins_section_transform_alter(&$transformation) {
  foreach ($transformation['regions'] as $region => $components) {
    foreach ($components as &$component) {
      os2uol_transform_plugins_layout_blocks_pre_transform($component);
    }
  }
}

function os2uol_transform_plugins_layout_blocks_pre_transform(&$block_transform): void {
  if ($block_transform instanceof EntityTransform) {
    $entity = $block_transform->getEntity();

    // Handle dynamic image styles for image block.
    if ($entity->getEntityTypeId() == 'block_content' && $entity->bundle() == 'image') {
      if ($entity->get('field_dynamic_height')->value) {
        $transform_mode = $block_transform->getValue('transform_mode');

        $new_transform_mode = $transform_mode . '_dynamic';

        $block_transform->setValue('transform_mode', $new_transform_mode);
        $block_transform->setTransformMode($new_transform_mode);
      }
    }
  }
}

function os2uol_transform_plugins_user_transform_alter(&$transformation) {
  if (empty($transformation)) {
    return;
  }

  /** @var \Drupal\user\Entity\User $user */
  $user = $transformation['#entity'];

  // Add user profile link and user roles to transformation.
  $transformation['link'] = $user->toUrl()->toString();
  $transformation['roles'] = $user->getRoles();

  $roles = $user->getRoles(TRUE);
  $role_id = reset($roles) ?? NULL;

  // Add user role label to transformation as bundle label.
  if ($role_id) {
    $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($role_id);
    $transformation['bundle_label'] = $role->label();
  }

  if ($transformation['transform_mode'] == 'default') {
    // Add related content
    $transformation['related_content'] = new ViewTransform('related_content', 'block_1');
  }
}

function os2uol_transform_plugins_view_latest_news_block_1_transform_alter(&$transformation) {
  if (empty($transformation)) {
    return;
  }
  $transformation['entity_type'] = 'block_content';
  $transformation['bundle'] = $transformation['view_id'];
}

/**
 * Implements hook_HOOK_transform_alter().
 */
function os2uol_transform_plugins_view_content_search_transform_alter(&$transformation) {
  if (!str_starts_with($transformation['display_id'], 'block_')) {
    return;
  }
  $transformation['entity_type'] = 'block_content';
  $transformation['bundle'] = $transformation['view_id'];
}

/**
 * Implements hook_HOOK_transform_alter().
 */
function os2uol_transform_plugins_view_course_providers_transform_alter(&$transformation) {
  if (!str_starts_with($transformation['display_id'], 'block_')) {
    return;
  }
  $transformation['entity_type'] = 'block_content';
  $transformation['bundle'] = $transformation['view_id'];
}

/**
 * Implements hook_HOOK_transform_alter().
 */
function os2uol_transform_plugins_view_transform_alter(&$transformation) {
  if (!empty($transformation['exposed_filters']['sort_by'])) {
    $transformation['exposed_filters']['sort_by']['default_value'] = $transformation['exposed_filters']['sort_by']['value'];
    unset($transformation['exposed_filters']['sort_by']['value']);
  }
}

/**
 * Implements hook_views_post_build().
 */
function os2uol_transform_plugins_views_post_build(\Drupal\views\ViewExecutable $view): void {
  if ($view->id() == 'related_content') {
    $options = $view->exposed_widgets['target_group']['#options'];

    foreach ($options as $key => $option) {
      if ($key == 'All') {
        continue;
      }

      $new_option = t('Progress to @option', ['@option' => strtolower($option)]);

      $view->exposed_widgets['target_group']['#options'][$key] = $new_option;
    }
  }
}
