<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() to restrict author editing.
 */
function author_limit_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Check if the form is the node edit form.
  if (in_array($form_id,
    array(
      'node_course_form',
      'node_course_educators_form',
      'node_exercise_form',
      'node_internship_form',
      'node_news_form',
      'node_page_form',
      'node_course_edit_form',
      'node_course_educators_edit_form',
      'node_exercise_edit_form',
      'node_internship_edit_form',
      'node_news_edit_form',
      'node_page_edit_form'
    )))
  {
    $user = \Drupal::currentUser();
    $roles = $user->getRoles();

    // Check if the user has the editor role.
    if (in_array('editor', $roles)) {
      // Modify the uid field to use the entity reference view.
      if (isset($form['uid']['widget'][0]['target_id'])) {
        $element = &$form['uid']['widget'][0]['target_id'];
        $element['#selection_handler'] = 'views';
        $element['#selection_settings'] = [
          'view' => [
            'view_name' => 'users_by_domain', // replace with your view name
            'display_name' => 'entity_reference_1', // replace with your view display name
          ],
        ];
      }
    }
  }
}
