os2uol_settings.settings:
  type: config_object
  label: 'OS2UOL Settings settings'
  mapping:
    logo:
      type: string
      label: 'Logo'
    font:
      type: string
      label: 'Font'
    primary_background_color:
      type: string
      label: 'Primary background color'
    primary_background_text_color:
      type: string
      label: 'Primary background text color'
    secondary_background_color:
      type: string
      label: 'Secondary background color'
    secondary_background_text_color:
      type: string
      label: 'Secondary background text color'
    text_positive_color:
      type: string
      label: 'Text positive color'
    text_negative_color:
      type: string
      label: 'Text negative color'
    site_tracking_script:
      type: string
      label: 'Site tracking script'
    free_course_application_reference:
      type: reference
      label: 'Free course application page'
    email_signature:
      type: map
      label: 'Email signature'
      mapping:
        value:
          type: string
          label: 'Email signature value'
        format:
          type: string
          label: 'Email signature format'
    from_reply_to_email:
      type: string
      label: 'From and Reply-To Email'
    free_course_email_signature:
      type: map
      label: 'Free course email signature'
      mapping:
        value:
          type: string
          label: 'Free course email signature value'
        format:
          type: string
          label: 'Free course email signature format'
    transport_pool_email_signature:
      type: map
      label: 'Transport pool email signature'
      mapping:
        value:
          type: string
          label: 'Transport pool email signature value'
        format:
          type: string
          label: 'Transport pool email signature format'
    theater_refund_email_signature:
      type: map
      label: 'Theater refund email signature'
      mapping:
        value:
          type: string
          label: 'Theater refund email signature value'
        format:
          type: string
          label: 'Theater refund email signature format'
