<?php
/**
 * @file
 * Provide a preview for entities in the frontend through Transform API.
 */

use Drupal\Core\Entity\ContentEntityTypeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\transform_api_preview\Form\TransformPreviewRedirectForm;

/**
 * Implements hook_entity_type_build().
 */
function transform_api_preview_entity_type_build(array &$entity_types) {
  $entity_types_with_preview = (array) \Drupal::config('transform_api_preview.settings')->get('entity_types');
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type instanceof ContentEntityTypeInterface && $entity_type->hasLinkTemplate('canonical') && in_array($entity_type_id, $entity_types_with_preview, TRUE)) {
      $entity_type->setFormClass('frontend', TransformPreviewRedirectForm::class);
      $entity_type->setLinkTemplate('frontend', $entity_type->getLinkTemplate('canonical') . '/frontend');
    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function transform_api_preview_entity_operation(EntityInterface $entity) {
  $operations = [];

  $supports_replicate = in_array(
    $entity->getEntityTypeId(),
    (array) \Drupal::config('transform_api_preview.settings')->get('entity_types')
  );

  if ($supports_replicate && $entity->hasLinkTemplate('frontend')) {
    $url = $entity->toUrl('frontend');

    if ($url->access()) {
      $operations['frontend'] = [
        'title' => t('Preview'),
        'weight' => 45,
        'url' => $url,
        'query' => [
          'destination' => NULL,
        ],
      ];
    }
  }

  return $operations;
}
