name: 'OS2udoglær Application Forms (GDPR)'
type: module
description: 'This module alters the application forms per GDPR requirements per domain.'
core_version_requirement: ^10 || ^11
package: 'OS2udoglær'
dependencies:
  - drupal:user
  - drupal:views
  - drupal:node
  - drupal:views_bulk_operations
  - drupal:content_moderation
  - os2uol_domain:os2uol_domain
