_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
langcode: da
theme: default
defaults:
  sender: symfony_mailer_lite
  formatter: symfony_mailer_lite
modules:
  sendgrid_integration: {  }
  symfony_mailer_lite: {  }
