"https://{default}/":
    type: upstream
    upstream: "frontend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"https://api.os2udoglaer.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.mitvadehav.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.aabenaalborg.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.klcviborg.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.laeringsportalenskive.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.rum.thisted.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.udoglaer.randers.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.udoglaer.vejle.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.ude.nu":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.ungegarantien.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://api.udsynmodarbejdsliv.dk":
    type: upstream
    upstream: "backend:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
