<?php

use Drupal\transform_api_facets\Transform\FacetTransform;

/**
 * Implements hook_HOOK_transform_alter().
 */
function transform_api_facets_view_transform_alter(&$transformation) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $transformation['#view'];

  $extender = $view->getDisplay()->getExtenders()['transform_api_facets'] ?? NULL;

  if ($extender === NULL) {
    return;
  }

  $transformation['facets'] = [];

  $enabled_facets = $extender->options['transform_facets'] ?? [];

  foreach ($enabled_facets as $facet_id => $enabled) {
    if (!$enabled) {
      continue;
    }

    $transformation['facets'][$facet_id] = new FacetTransform($facet_id);
  }
}
