<?php


/**
 * Define available fonts for the OS2UOL settings.
 */
function os2uol_settings_get_available_fonts(): array {
  return [
    'Arial' => 'Arial',
    'Montserrat' => 'Montserrat',
    'Open Sans' => 'Open Sans',
    'Roboto' => 'Roboto',
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for styles_preview.
 */
function os2uol_settings_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'styles_preview') {
    $suggestions[] = $hook . '__' . 'custom' . '__' . $variables['elements']['#collection'];
  }
}

/**
 * Implements hook_theme() for OS2UOL settings.
 */
function os2uol_settings_theme($existing, $type, $theme, $path) {
  return [
    'styles_preview__custom__color_theme' => [
      'base hook' => 'styles_preview',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for styles_preview.
 */
function os2uol_settings_preprocess_styles_preview(&$variables) {
  if ($variables['collection'] === 'color_theme') {
    $config = \Drupal::config('os2uol_settings.settings');
    $primary_bg_color = $config->get('primary_background_color');
    $primary_bg_txt_color = $config->get('primary_background_text_color');
    $secondary_bg_color = $config->get('secondary_background_color');
    $secondary_bg_txt_color = $config->get('secondary_background_text_color');

    if ($variables['style'] === 'theme-primary' && !empty($primary_bg_color) && !empty($primary_bg_txt_color)) {
      $variables['primary_bg_color'] = $primary_bg_color;
      $variables['primary_bg_txt_color'] = $primary_bg_txt_color;
    }

    if ($variables['style'] === 'theme-secondary' && !empty($secondary_bg_color) && !empty($secondary_bg_txt_color)) {
      $variables['secondary_bg_color'] = $secondary_bg_color;
      $variables['secondary_bg_txt_color'] = $secondary_bg_txt_color;
    }
  }
}
