os2uol_settings.domain_settings:
  path: '/admin/domain-settings'
  defaults:
    _title: 'Domain settings'
    _form: 'Drupal\os2uol_settings\Form\DomainSettingsForm'
  requirements:
    _permission: 'use domain config ui'
