<?php

use Drupal\domain\Entity\Domain;
use Drupal\os2uol_domain\Os2uolDomain;

/**
 * Implements hook_entity_create().
 */
function os2uol_domain_entity_create(\Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::service('os2uol_domain.default_domain')->entityCreate($entity);
}

/**
 * Implements hook_options_list_alter().
 */
function os2uol_domain_options_list_alter(array &$options, array $context) {
  /** @var \Drupal\Core\Field\FieldDefinitionInterface $fieldDefinition */
  $fieldDefinition = $context['fieldDefinition'];
  if (isset($fieldDefinition->getSettings()['target_type'])) {
    $target_type = $fieldDefinition->getSettings()['target_type'];
  } else {
    $target_type = '';
  }
  if ($fieldDefinition->getType() == 'entity_reference' && $target_type == 'taxonomy_term') {
    $handler_settings = $fieldDefinition->getSettings()['handler_settings'];
    $target_bundles = $handler_settings['target_bundles'];
    if (count($target_bundles) == 1) {
      $target_bundle = reset($target_bundles);
      /** @var \Drupal\Core\Entity\EntityFieldManagerInterface $entityFieldManager */
      $entityFieldManager = \Drupal::service('entity_field.manager');
      $fields = $entityFieldManager->getFieldDefinitions($target_type, $target_bundle);
      if (isset($fields['domain_access'])) {
        $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
        if ($user->get('field_domain_all_affiliates')->getString() == 1) {
          return;
        }
        $term_storage = \Drupal::entityTypeManager()->getStorage($target_type);
        $query = $term_storage->getQuery()
          ->condition('vid', $target_bundle)
          ->condition('status', 1);
        $domains = [];
        foreach ($user->get('field_domain_access')->getValue() as $item) {
          $domains[] = $item['target_id'];
        }
        if (empty($domains)) {
          $query->notExists('domain_access');
        } else {
          $group = $query->orConditionGroup()
            ->notExists('domain_access')
            ->condition('domain_access.target_id', $domains, 'IN');
          $query->condition($group);
        }
        $tids = $query
          ->accessCheck(FALSE)
          ->sort('weight')
          ->sort('name')
          ->execute();
        $terms = $term_storage->loadMultiple($tids);
        if (isset($options['_none'])) {
          $options = [
            '_none' => t('- None -'),
          ];
        } else {
          $options = [];
        }
        foreach ($terms as $term) {
          $options[$term->id()] = $term->label();
        }
      }
    }
  }
}

/**
 * Implements hook_views_data_alter().
 */
function os2uol_domain_views_data_alter(array &$data) {
  $data['user__field_domain_access']['current_all'] = [
    'title' => t('Current domain (user)'),
    'group' => t('Domain'),
    'filter' => [
      'id' => 'domain_access_user_current_filter',
      'field' => 'field_domain_access_target_id',
      'table' => 'user__field_domain_access',
      'field_name' => 'field_domain_access',
      'title' => t('Has access to current domain'),
      'help' => t('Filters out users having access to current domain.'),
      'type' => 'yes-no',
    ],
  ];

  $data['views']['headless_base_url'] = [
    'title' => t('Headless Base url'),
    'help' => t("Site's base url based on headless domain simple sitemap settings."),
    'field' => [
      'id' => 'headless_base_url',
    ],
  ];
}

/**
 * @param \Drupal\node\NodeInterface $node
 *
 * @return \Drupal\domain\Entity\Domain|null
 */
function os2uol_domain_get_domain_from_node(\Drupal\node\NodeInterface $node): Domain|null {
  if (!$node->hasField('field_domain_access')) {
    return NULL;
  }

  $entity_domains = array_column($node->get('field_domain_access')->getValue(), 'target_id');

  // Remove default domain from the list.
  $default_domain = Os2uolDomain::DEFAULT_DOMAIN_ID;
  $entity_domains = array_diff($entity_domains, [$default_domain]);

  if (empty($entity_domains)) {
    return NULL;
  }

  // Get the first domain from the list.
  $domain_id = reset($entity_domains);
  $domain = Domain::load($domain_id);

  return $domain;
}
