<?php

use Drupal\atoms\Atom;
use Drupal\Core\Cache\Cache;

/**
 * Implements hook_entity_transform_alter().
 * @param array $transformation
 */
function os2uol_video_block_entity_transform_alter(array &$transformation)
{
  // Check if the transformation is for a video paragraph.
  if (
    $transformation['type'] == 'entity'
    && $transformation['bundle'] == 'video'
    && $transformation['entity_type'] == 'paragraph'
  ) {
    // Load the video_overlay_text atom.
    $atom = Atom::load('video_overlay_text');

    // Add the video_overlay_text atom to the transformation.
    $transformation['video_overlay_text'] = $atom->view()->toString();

    // Add cache tag
    $transformation['#cache']['tags'] = Cache::mergeTags($transformation['#cache']['tags'], $atom->getCacheTags());
  }
}
