<?php

use Drupal\atoms\Atom;
use Drupal\Core\Cache\Cache;

/**
 * Implements hook_ENTITY_TYPE_transform_alter().
 * @param array $transformation
 */
function os2uol_video_block_paragraph_transform_alter(array &$transformation): void {
  // Check if the transformation is for a video paragraph.
  if ($transformation['bundle'] == 'video') {
    // Load the video_overlay_text atom.
    $atom = Atom::load('video_overlay_text');

    // Add the video_overlay_text atom to the transformation.
    $transformation['video_overlay_text'] = $atom->view()->toString();

    // Add cache tag
    $transformation['#cache']['tags'] = Cache::mergeTags($transformation['#cache']['tags'], $atom->getCacheTags());
  }
}
