name: Auto Merge Release Branches to Staging

on:
  push:
    branches:
      - "release/**"
jobs:
  announce:
    name: Announce deploy to Slack
    environment: Staging
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
    steps:
      - name: Announce to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
          text: "There is a deployment to *${{ github.ref }}* underway :oooo:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  merge-to-staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Merge release branch to staging
        run: |
          git fetch origin
          git checkout staging
          git merge ${{ github.ref }} --no-ff -m "Merging release branch ${{ github.ref }} into staging"
          git push origin staging