name: Update the common Platform.sh Repository

on:
  push:
    branches:
      - "release/**"
      - "main"

jobs:
  update-platform-repo:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Update the Platform Repo Submodule for Backend
        run: |
          repo_owner="os2ulf"
          repo_name="os2udoglaer-platform"
          event_type="update-submodule"

          # Get the latest commit hash
          commit_hash=${{ github.sha }}

          # Get the branch name
          branch_name=${{ github.ref_name }}

          # If the branch isn't main, it's staging!
          if [ "$branch_name" != "main" ]; then
            branch_name="staging"
          fi

          # Valid branches are main and staging, fail on anything else
          if [ "$branch_name" != "main" ] && [ "$branch_name" != "staging" ]; then
            echo "Invalid branch name: $branch_name"
            exit 1
          fi

          # Echo out the above variables
          echo "Commit Hash: $commit_hash"
          echo "Branch Name: $branch_name"
          echo "Repository Owner: $repo_owner"
          echo "Repository Name: $repo_name"
          echo "Event Type: $event_type"
          echo "URL: https://api.github.com/repos/$repo_owner/$repo_name/dispatches"
          echo "Payload: {\"event_type\": \"$event_type\", \"client_payload\": {\"submodule\": \"backend\", \"branch\": \"$branch_name\", \"commit\": \"$commit_hash\"}}"

          # Create a client payload

          # Trigger the repository dispatch event
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"submodule\": \"backend\", \"branch\": \"$branch_name\", \"commit\": \"$commit_hash\"}}"
