name: Update the common Platform.sh Repository

on:
  push:
    branches:
      - 'release/**'
      - 'main'

jobs:
  update-platform-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Update the Platform Repo Submodule for Backend
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: os2ulf/os2udoglaer
          event-type: update-submodule
          client-payload: '{"submodule": "backend", "branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}"}'
